# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build Example tbkmini nice_nano_v2"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["tukon_left nice_view_adapter nice_view","tukon_right nice_view_adapter nice_view"]'
